import os
import shutil
import json
from datetime import datetime
from pathlib import Path

"""
Post-generation script — only creates sdk_build.py and cleans up.

"""

PROJECT_DIR = str(Path(os.path.dirname(__file__), '..', '..'))
BASE_PATH = os.path.join(PROJECT_DIR, 'chkp_ai_security_sdk')

PKG_NAME = 'chkp_ai_security_sdk'

PRODUCTS = [
    # ── Sync ──
    {
        'label': 'ai-security',
        'generated_dir': os.path.join(BASE_PATH, 'generated'),
        'spec_dir': os.path.join(PROJECT_DIR, 'resources', 'specs', 'main'),
    },
    {
        'label': 'browse-security',
        'generated_dir': os.path.join(BASE_PATH, 'generated_browse'),
        'spec_dir': os.path.join(PROJECT_DIR, 'resources', 'specs', 'browse'),
    },
    # ── Async ──
    {
        'label': 'ai-security-async',
        'generated_dir': os.path.join(BASE_PATH, 'generated_async'),
        'spec_dir': os.path.join(PROJECT_DIR, 'resources', 'specs', 'main'),
    },
    {
        'label': 'browse-security-async',
        'generated_dir': os.path.join(BASE_PATH, 'generated_browse_async'),
        'spec_dir': os.path.join(PROJECT_DIR, 'resources', 'specs', 'browse'),
    },
]


def __prepare_build_info(product):
    output_path = product['generated_dir']
    spec_path = product['spec_dir']

    with open(os.path.join(spec_path, 'swagger.json'), 'r') as f:
        swagger_spec = json.load(f)
    with open(os.path.join(spec_path, 'spec'), 'r') as f:
        spec_name = f.readline().strip()

    build_data = {
        'sdk_build': os.environ.get('BUILD_JOB_ID', ''),
        'sdk_version': os.environ.get('BUILD_VERSION', ''),
        'spec': spec_name,
        'spec_version': swagger_spec['info']['version'],
        'released_on': datetime.now().isoformat(),
    }

    with open(os.path.join(output_path, 'sdk_build_data.json'), 'w') as f:
        json.dump(build_data, f)

    pkg_name = PKG_NAME
    content = f'''import json
import os
from {pkg_name}.classes.workforceai_sdk_info import WorkforceAISDKInfo

def sdk_build_info() -> WorkforceAISDKInfo:
    data_path = os.path.join(os.path.dirname(__file__), 'sdk_build_data.json')
    with open(data_path, 'r') as f:
        data = json.load(f)
    return WorkforceAISDKInfo(**data)
'''
    with open(os.path.join(output_path, 'sdk_build.py'), 'w') as f:
        f.write(content)
    print(f'[post-build:{product["label"]}] sdk_build.py written')


def __cleanup_generated(product):
    output_path = product['generated_dir']
    for dirname in ['test', 'docs']:
        path = os.path.join(output_path, dirname)
        if os.path.exists(path):
            shutil.rmtree(path)
            print(f'[post-build:{product["label"]}] Removed {path}')
    # Clean test dir at project root if generator created one
    test_root = os.path.join(PROJECT_DIR, 'test')
    if os.path.exists(test_root):
        shutil.rmtree(test_root)
    # Remove generated README files
    for readme_name in ['generated_README.md', 'README.md']:
        readme_path = os.path.join(BASE_PATH, readme_name)
        if os.path.exists(readme_path):
            os.remove(readme_path)
            print(f'[post-build:{product["label"]}] Removed {readme_path}')
    # Remove legacy api_mixin.py if it exists (now generated by template)
    legacy = os.path.join(output_path, 'api_mixin.py')
    if os.path.exists(legacy):
        os.remove(legacy)
        print(f'[post-build:{product["label"]}] Removed legacy api_mixin.py')


def post_build_process():
    for product in PRODUCTS:
        label = product['label']
        print(f'[post-build:{label}] Preparing build info...')
        __prepare_build_info(product)
        print(f'[post-build:{label}] Cleaning up generated files...')
        __cleanup_generated(product)

    print('[post-build] Setting __init__ export...')
    shutil.copy(
        os.path.join(BASE_PATH, '__init__template.py'),
        os.path.join(BASE_PATH, '__init__.py'),
    )
    print('[post-build] Done.')
